settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: wms-laowanhui
    name: laowanhui
    url: 'https://wms.laowanhui.com/'
    method: GET
    expectStatus: 200
  - id: wms-fuqueyun
    name: fuqueyun
    url: 'https://wms.fuqueyun.com/'
    method: GET
    expectStatus: 200
  - id: wms-sfcchina
    name: sfcchina
    url: 'https://newwms.sfcchina.com.cn/'
    method: GET
    expectStatus: 200
  - id: wms-yihetang
    name: yihetang
    url: 'https://wms.yihetang.com/'
    method: GET
    expectStatus: 200

